### ISSUE TITLE
Support CSS?

### ISSUE THREAD

**Issue by developit** [GoogleChrome/preload-webpack-plugin#18]
Thought: would it be useful to detect and support CSS via `as="style"`?
Example within an `html-webpack-plugin` template [here](https://github.com/developit/preact-www/blob/master/src/index.html#L15-L21).

**Comment by addyosmani** [comment]
I would be more than happy to have support for `as=style` here. I didn't get a chance to add the detection at release, but would be happy to land a PR if someone wanted to noodle on it, @developit :)

**Comment by addyosmani** [comment]
@developit @laysent started this work over in https://github.com/GoogleChrome/preload-webpack-plugin/pull/29. Anything else we can do to improve the DX of that flow?

**Comment by addyosmani** [comment]
This feature is now supported as of #29.
