### ISSUE TITLE
Chrome warning

### ISSUE THREAD

**Issue by jameslnewell** [GoogleChrome/preload-webpack-plugin#24]
Hi!

I'm not using `html-webpack-plugin` but am using the strategy implemented by this plugin to `preload` my async chunks which are the result of code-splitting per route. The HTML looks like this:

```
<link rel="preload" href="/client.0.js" as="script"/>
<link rel="preload" href="/client.1.js" as="script"/>
```

When I load the page, only one of the of the chunks are actually used until the user navigates to the other route. Chrome gives me this warning:

```
The resource http://localhost:3000/client.1.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```

According to the network tab, when on the `client.1.js` route, the `client.0.js` chunk is always being loaded first because of the `preload`s and this appears to have a detrimental impact on perf (compared to not using `preload`s). It results in the user downloading all the JavaScript, even if the user will never visit all of the routes (probably doesn't matter on desktop but on mobile it'd be nice not to download the extra bytes and save my mobile data).

![image](https://cloud.githubusercontent.com/assets/2237996/23631485/cd0a23f2-0312-11e7-91ce-791b97c5773f.png)

Is there a better strategy that can be implemented? I imagine such a strategy would involve a lot more manual guessing (specific to each app) and require named chunk imports (https://github.com/webpack/webpack/issues/1949) to manually insert a `preload` (e.g. when a user has scrolled 90% of the way to the CTA)??

---

Not sure if this is what https://github.com/GoogleChrome/preload-webpack-plugin/issues/11 was getting at.

**Comment by ykzts** [comment]
@jameslnewell https://bugs.chromium.org/p/chromium/issues/detail?id=655698 Is this the same problem?

**Comment by jameslnewell** [comment]
@ykzts nah I don't think so. The `preload`ed scripts aren't executed unless desired.

**Comment by jameslnewell** [comment]
I'm attending the PWA roadshow in Sydney today. One of the staff suggested caching all of an app's assets using a service worker since they add up to less than a mb... so maybe loading unused bytes doesn't have a huge impact, but still the impact on the meaningful-first-render isn't ideal.

**Comment by addyosmani** [comment]
Hey @jameslnewell. This might be too high-level to help, but in general I strongly suggest only preloading late-discovered resources in the page that are _definitely_ needed by the page. If the chunks for the route are not going to be used, there's no reason to be preloading them. Prefetch them if you think the user might need them otherwise.

I wrote up a post on preload and prefetch priorities that might help clear some of this up: https://medium.com/@addyosmani/preload-prefetch-and-priorities-in-chrome-776165961bbf

**Comment by jameslnewell** [comment]
Cool, thats what I thought from reading the docs but from the plugin's default behavior I ASSuMEd that preloading all the async scripts was suggested.

Your article answers my questions very clearly, thanks! 🙏
