### ISSUE TITLE
Chrome net error

### ISSUE THREAD

**Issue by sofiia-hlyniana** [GoogleChrome/preload-webpack-plugin#25]
Using preload plugin causes ERR_INSUFFICIENT_RESOURCES in Chrome Version 56.0.2924.87 (64-bit).
My webpack settings : 
```
  new PreloadWebpackPlugin({
    rel           : 'prefetch',
    include       : 'all',
    fileBlacklist : [/\.js\.map/, /app*.*\.js/, /vendor*.*\.js/]
  })
```

**Comment by ragingwind** [comment]
As I know, the browser warns ERR_INSUFFICIENT_RESOURCES when it manages a lot of request. Would you check the status of network in DevTools

**Comment by addyosmani** [comment]
Hey @sofiia-hlyniana. Sorry for the delayed reply! Could you let me know if you're running into the same issue in Canary? If you happen to have a repro up somewhere with your app also happy to look into it more closely.

**Comment by addyosmani** [comment]
Hey again @sofiia-hlyniana. I haven't been able to reproduce this issue when testing it out in recent versions of Chrome. I'm going to go ahead and close this issue, but if you're able to reproduce the issue still please let us know and we'll reopen this.
