### ISSUE TITLE
How to preload fonts?

### ISSUE THREAD

**Issue by glebmachine** [GoogleChrome/preload-webpack-plugin#28]
I would like to be able to preload fonts like in this article:
https://shopifyengineering.myshopify.com/blogs/engineering/how-17-lines-of-code-improved-shopify-com-loading-by-50

**Comment by addyosmani** [comment]
This plugin is currently optimized to focus on preloading script bundles, but we're exploring expanding this in https://github.com/GoogleChrome/preload-webpack-plugin/pull/29. I've added a note to suggest we include support for fonts in there too.

**Comment by addyosmani** [comment]
@glebmachine There's discussion about supporting Web Font preloading in https://github.com/GoogleChrome/preload-webpack-plugin/pull/29. Specifically https://github.com/GoogleChrome/preload-webpack-plugin/pull/29/commits/99c5dab802447115cc97fac9e69e0cf54a1cd5fd is one of the commits adding this.

Could you let us know over there is anything you would consider missing there?

**Comment by glebmachine** [comment]
Great! Thank you)

**Comment by gkatsanos** [comment]
Just to clarify, there's no way to automatically inject <link>s to do font-preloading currently now -
 right?
