### ISSUE TITLE
Peer Dependency Webpack 3

### ISSUE THREAD

**Issue by malikshahzad228** [GoogleChrome/preload-webpack-plugin#30]
Peer is outdated

**Comment by malikshahzad228** [comment]
This issue has a PR: [https://github.com/GoogleChrome/preload-webpack-plugin/pull/31](https://github.com/GoogleChrome/preload-webpack-plugin/pull/31)

**Comment by addyosmani** [comment]
Thanks for calling this out. Landed #31!
