### ISSUE TITLE
css preload also includes the synchronous link

### ISSUE THREAD

**Issue by roma98** [GoogleChrome/preload-webpack-plugin#32]
Hello everyone,
I'm currently working on a react app ejected from create-react-app, and in a quest of getting the shortest loading time (and highest pagespeed insight score I admit), I have decided to load everything asynchronously in index.html, and inline a critical css.
So far I've used ScriptExtHtmlWebpackPlugin to async load the main js file.
After that I still got a warning because of a blockig main css file, and I was happy to find this project.

This is how I got it configured : 

    new ScriptExtHtmlWebpackPlugin({
        defaultAttribute: 'async'
    }),
    new PreloadWebpackPlugin({
        rel: 'preload',
        as: 'style',
        include: 'all',
        fileBlacklist: [/\.map|.js/]
    }),

I've excluded js files since I only wanted to target the css.

and this is what I got at the end

`<link rel="preload" href="/static/css/main.f5b70207.css" as="style">`
`<link href="/static/css/main.f5b70207.css" rel="stylesheet">`

Maybe I've missed something, but how come we get 2 links here? Would it be possible to only get the preload one?

**Comment by roma98** [comment]
I have found a workaroudn by using `style-ext-html-webpack-plugin` in addition to `script-ext-html-webpack-plugin` to achieve what I need.

**Comment by praneshr** [comment]
@roma98 I'm facing the sample problem. Mind if you share how to solve it? 😃

**Comment by roma98** [comment]
hey @praneshr ! import `script-ext-html-webpack-plugin` and add `        new ScriptExtHtmlWebpackPlugin({
            defaultAttribute: 'async'
        }),` in plugins

**Comment by roma98** [comment]
@praneshr sorry I meant import `style-ext-html-webpack-plugin` and add `new StyleExtHtmlWebpackPlugin()` in plugins

**Comment by FL0RIANMEYER** [comment]
Same issue with
"webpack": "^4.8.3",
"preload-webpack-plugin": "^3.0.0-alpha.3",
"html-webpack-plugin": "^3.2.0",

using this config:

```javascript
    config.plugins.push(new HtmlWebpackPlugin({
        inject: true,
        template: PATHS.client + '/index.html',
        filename: 'index.html',
    }));


    config.plugins.push(new PreloadWebpackPlugin({
        rel: 'preload',
        include: 'allChunks',
    }));
```

Same error with option include: 'allAssets'. Without include nothing was injected to index.html output.

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Todo MVC---ASS--</title>
    <link as="script" href="client.js" rel="preload">
<link as="style" href="client.styles.css" rel="preload">
<link as="script" href="runtime~client.js" rel="preload">
<link href="client.styles.css" rel="stylesheet"></head>

    <body>
      <div id="root">{{#html}}{{{html}}}{{/html}}</div>

        <script>window.storeState={{{state}}}</script>
      {{{style}}}
    <script type="text/javascript" src="runtime~client.js"></script>
    <script type="text/javascript" src="client.js"></script></body>
</html>
```


with [html-webpack-plugin@4.0.0-alpha](https://www.npmjs.com/package/html-webpack-plugin) I got this error:

```
TypeError: Cannot convert undefined or null to object
  - values
  
  - index.js:81 
    [webServer]/[preload-webpack-plugin]/build/index.js:81:49
  
  - Array.filter
  
  - index.js:77 PreloadPlugin.addLinks
    [webServer]/[preload-webpack-plugin]/build/index.js:77:23
  
  - index.js:163 
    [webServer]/[preload-webpack-plugin]/build/index.js:163:37
  
  - new Promise
  
  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [webServer]/[tapable]/lib/Hook.js:35:21
  
  - index.js:180 Promise.resolve.then.then.then.then.then.then.html
    [webServer]/[html-webpack-plugin]/index.js:180:99
  
  - next_tick.js:160 process._tickCallback
    internal/process/next_tick.js:160:7
```

[style-ext-html-webpack-plugin@3.4.7](https://www.npmjs.com/package/style-ext-html-webpack-plugin) isnt working with Webpack 4.

Does anyone have a better solution for **Css as a link and Js as script tag with preload and defer**?

Please reopen!
