### ISSUE TITLE
Semantic version is incorrect.

### ISSUE THREAD

**Issue by talamaska** [GoogleChrome/preload-webpack-plugin#33]
between 1.2.2 and 1.2.3 you switch the peer dependency from webpack 2.x to v3.x. I should say that this is quite breaking change. Now because the package.json was set with ^1.2.2 it installed 1.2.3 thinking it's OK, except it's not. Please consider changing the major version.

**Comment by addyosmani** [comment]
This was an unfortunate oversight on my part. I'll get this addressed in the next version bump.

**Comment by addyosmani** [comment]
@talamaska I went back and read through the Angular Starter issue where you'd originally noted this problem. I'd like to ensure that users on both Webpack 2.2.x and Webpack 3.x are able to use this plugin effectively and rethinking our peer dependencies (beyond just doing the major version bump, as I've done for 2.x) may be needed.

Currently considering using a similar approach to https://github.com/jantimon/html-webpack-plugin/blob/master/package.json#L66. Would this have addressed the original conflict concerns you had?

**Comment by talamaska** [comment]
@addyosmani Thanks for taking time to investigate. I think it will resolve my concerns. The thing is that is seems that the Angular Starter from AngularClass is not really supported and we might not see the upgrade to webpack 3. It is possible that other dependencies are as well stuck on webpack 2 and the upgrade might not be smooth. I might actually go forward and switch to ng cli. Do you have an opinion on that?
