### ISSUE TITLE
invalid configuration object

### ISSUE THREAD

**Issue by agdolla** [GoogleChrome/preload-webpack-plugin#5]
when I try to run the demo I get:

npm run prod

Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'inject'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }

osx, node 6.9.1, npm 4.1.1

**Comment by addyosmani** [comment]
Could you let me know what global version of Webpack you were using?

**Comment by agdolla** [comment]
I do not have it installed globally, so the local one is used
./node_modules/.bin/webpack -v
2.2.1

**Comment by kuldeepkeshwar** [comment]
I'm also facing same issue 

```
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'inject'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }
197NODMB17820:demo kuldeepkeshwar$  node_modules/.bin/webpack -v
2.2.1
```

**Comment by addyosmani** [comment]
I haven't been able to reproduce this I'm afraid. Let me kill my local node_modules and try again.

**Comment by addyosmani** [comment]
Hey @agdolla and @kuldeepkeshwar. Could you let me know if this fixes the issue for you?

Edit webpack.config.js and remove `inject`: 

```diff
  plugins: plugins,
  devServer: {
    contentBase: './client',
    historyApiFallback: true,
-   inject: true,
    port: 3000,
```

Run `npm run prod`. Does that work for you?

**Comment by kuldeepkeshwar** [comment]
@addyosmani it is working now 
although there is an error related to sw, it is not able to find sw.js

![screen shot 2017-02-03 at 9 13 04 am](https://cloud.githubusercontent.com/assets/10448534/22578769/3274eab4-e9f1-11e6-929f-684d70c155a1.png)

**Comment by agdolla** [comment]
yeah, I did it myself already and works for me

**Comment by agdolla** [comment]
what does inject:true means anyway ? I could not find it
